UPDATE SALES.DREAMCRAFT.`CUSTOMERS`
SET `STATE`='NA'
WHERE `STATE` IS NULL;

UPDATE SALES.DREAMCRAFT.`OFFICES`
SET `STATE`='NA'
WHERE `STATE` IS NULL;

UPDATE SALES.DREAMCRAFT.`ORDERS`
SET `COMMENTS`='NA'
WHERE `COMMENTS` IS NULL;

UPDATE SALES.DREAMCRAFT.`ORDERS`
SET `SHIPPEDDATE`='0'
WHERE `SHIPPEDDATE` IS NULL;

UPDATE SALES.DREAMCRAFT.`EMPLOYEES`
SET `REPORTSTO`=0
WHERE `REPORTSTO` IS NULL;

UPDATE SALES.DREAMCRAFT.`CUSTOMERS`
SET `SALESREPEMPLOYEENUMBER`=0
WHERE `SALESREPEMPLOYEENUMBER` IS NULL;