ALTER TABLE SALES.DREAMCRAFT.`PRODUCTS`
ADD `MARKUP_PERCENTAGE` DOUBLE;

UPDATE SALES.DREAMCRAFT.`PRODUCTS`
SET `MARKUP_PERCENTAGE` =
ROUND((`MSRP` - `BUYPRICE`) / `BUYPRICE` * 100, 2);

ALTER TABLE SALES.DREAMCRAFT.`ORDERDETAILS`
ADD `TOTAL_COST` DOUBLE;

UPDATE SALES.DREAMCRAFT.`ORDERDETAILS`
SET `TOTAL_COST` =
`QUANTITYORDERED` * `PRICEEACH`;